clc; clear; close all;

%% 1. AI Prediction (Decide the Scheme)
% Import the ONNX network generated by Python
net = importONNXNetwork('adaptive_mod_model.onnx', 'OutputLayerType', 'classification');

% Enter your current lab hardware measurements here:
% [Tx_Power_dBm, Target_SNR_dB, Mean_Channel_Gain, Noise_Power_Watts, Phase_Noise_Var]
current_lab_features = [0, 15.0, 0.5, 0.001, 0.01];

% Standardize features
py_mean = [19.99548187,20.00425125,  0.97763703,  0.02361063,  0.03]
py_var = [3.32665565e+01, 1.32839117e+02, 8.81834681e-06, 5.42012102e-03,0.00000000e+00]

features_scaled = (current_lab_features - py_mean) ./ sqrt(py_var);

% Predict
pred_scores = predict(net, dlarray(features_scaled, 'CB'));
[~, scheme_idx] = max(extractdata(pred_scores));
scheme_idx = scheme_idx - 1; % 0=BPSK, 1=QPSK, 2=8PSK, 3=16QAM, 4=64QAM, 5=256QAM

schemes = ["BPSK", "QPSK", "8PSK", "16QAM", "64QAM", "256QAM"];
bits_per_symbol = [1, 2, 3, 4, 6, 8];
M_vals = [2, 4, 8, 16, 64, 256];

chosen_scheme = schemes(scheme_idx + 1);
M = M_vals(scheme_idx + 1);
bps = bits_per_symbol(scheme_idx + 1);
fprintf('AI Selected Scheme: %s\n', chosen_scheme);

%% 2. Data Preparation
% Dummy payload bits (replace with your image/text bits)
num_payload_bits = 2048 * bps; % Ensure integer multiple of symbol size
payload_bits = randi([0 1], num_payload_bits, 1);

% BPSK Header (64-bit Sync + 16-bit Scheme ID)
h_pn = comm.PNSequence('Polynomial',[6 5 0], 'SamplesPerFrame', 64, 'InitialConditions',[0 0 0 0 0 1]);
sync_bits = step(h_pn);
scheme_header_bits = dec2bin(scheme_idx, 16)' - '0';
header_bits = [sync_bits; scheme_header_bits(:)];

%% 3. Modulation
% 3a. Header is ALWAYS BPSK (so RX can always decode it)
header_syms = pskmod(header_bits, 2, 'InputType', 'bit');

% 3b. Payload is adaptively modulated
if contains(chosen_scheme, 'PSK')
    payload_syms = pskmod(payload_bits, M, 'InputType', 'bit');
else
    payload_syms = qammod(payload_bits, M, 'InputType', 'bit', 'UnitAveragePower', true);
end

% Combine (Complex Baseband Signal)
tx_syms = [header_syms; payload_syms];

%% 4. Pulse Shaping & Digital Upconversion (Single Wire Multiplexing)
sps = 8; % High samples per symbol needed for subcarrier
tx_up = upsample(tx_syms, sps);
h_rrc = comm.RaisedCosineTransmitFilter('RolloffFactor', 0.35, 'FilterSpanInSymbols', 6, 'OutputSamplesPerSymbol', sps);
tx_baseband = step(h_rrc, tx_up);

% DIGITAL SUBCARRIER: This is the magic that puts I and Q on one wire.
% We mix the baseband to a 500 kHz digital IF.
F_sample = 4e6; % 4 MS/s output rate to AWG
f_sub = 500e3;  % 500 kHz subcarrier
t = (0:length(tx_baseband)-1)' / F_sample;

% Multiply by carrier and take the REAL part -> 1D voltage array
tx_passband = real(tx_baseband .* exp(1j * 2 * pi * f_sub * t));

% Normalize for AWG
tx_passband = tx_passband / max(abs(tx_passband));

dlmwrite('Adaptive_Transmitted.csv', tx_passband, 'precision', 5);
fprintf('File generated. Play on AWG at 4 MS/s.\n');
